name: Multiverse-Core
main: com.onarandombox.MultiverseCore.MultiverseCore
authors: ['dumptruckman', 'Rigby', 'fernferret', 'lithium3141', 'main--']
website: 'https://dev.bukkit.org/projects/multiverse-core'
softdepend: ['Vault']
api-version: 1.13
version: maven-version-number
commands:
  mv:
    description: Generic Multiverse Command
    usage: /<command>
  mvcreate:
    description: World create command
    aliases: [mvc]
    usage: |
            /<command> <world> <environment>
            /<command> creative normal -- Creates a world called 'creative' with a NORMAL environment.
            /<command> hellworld nether -- Creates a world called 'hellworld' with a NETHER environment.
  mvimport:
    description: World import command
    aliases: [mvim]
    usage: |
      /<command> <world> <environment> [-g generator[:id]] [-n]
      /<command> creative normal -- Imports an existing world called 'creative' with a NORMAL environment.
      /<command> hellworld nether -- Imports an existing world called 'hellworld' with a NETHER environment.
  mvremove:
    description: Remove world from multiverse command
    usage: |
            /<command> <world>
  mvdelete:
    description: Delete world from server folders command
    usage: |
            /<command> <world>
  mvunload:
    description: World unload command
    usage: |
            /<command> <world>
  mvmodify:
    description: Modify the settings of an existing world
    aliases: [mvm]
    usage: |
            /<command> <set|add|remove|clear> <value> <property> [world]
            /<command> set pvp false creative -- Turns off PVP in the 'creative' world.
  mvmset:
    description: Modify the settings of an existing world
    usage: |
            /<command> <value> <property> [world]
            /<command> pvp false creative -- Turns off PVP in the 'creative' world.
  mvmadd:
    description: Modify the settings of an existing world
    usage: |
            /<command> <value> <property> [world]
            /<command> sheep animals world_nether -- Add sheep to animal list for 'world_nether' world.
  mvmremove:
    description: Modify the settings of an existing world
    aliases: [mvmdelete]
    usage: |
            /<command> <value> <property> [world]
            /<command> sheep animals world_nether -- remove sheep from animal list for 'world_nether' world.
  mvmclear:
    description: Modify the settings of an existing world
    usage: |
            /<command> <property> [world]
            /<command> animals world_nether -- Empties animal list for 'world_nether' world.
  mvtp:
    description: Command to teleport between Worlds
    usage: |
            /<command> [player] <destination>
            Example: /<command> creative - Teleports you to the relevant location in the 'creative' world.
  mvlist:
    description: Print list of loaded Worlds
    aliases: [mvl]
    usage: |
            /<command> [page]
            Example: /<command> NETHER - Shows all NETHER Worlds.
            Example: /<command> NORMAL - Shows all NORMAL Worlds.
  mvsetspawn:
    description: Set the spawn area for a particular world
    aliases: [mvsets, mvss]
    usage: /<command> -- Sets the spawn area of the current world to your location.
  mvspawn:
    description: Teleport to the spawn area
    aliases: [mvs]
    usage: /<command> [player] -- Teleports you to the spawn area of your current world.
  mvcoord:
    description: Display World, Coordinates, Direction & Compression for a world.
    aliases: [mvco]
    usage: |
            /<command> [world]
            /<command> -- Shows the relevant coordinates in your current world.
            /<command> creative -- Shows the relevant coordinates if you were in the 'creative' world.
  mvwho:
    description: Display online users per world.
    aliases: [mvw]
    usage: |
            /<command> [world|--all]
            /<command> -- Shows who is online in each world.
            /<command> creative -- Shows who is online in the 'creative' world.
  mvreload:
    description: Reload Configuration files.
    aliases: [mvr]
    usage: /<command>
  mvpurge:
    description: Purge the targetted world of creatures.
    usage: |
            /<command> [WORLD|all] [all|animals|monsters|MOBNAME]
            /<command> -- Purges the players world of all creatures.
            /<command> creative all -- Purges the creative world of all Creatures.
            /<command> creative creeper -- Purges the creative world of all CREEPERS.
  mvconfirm:
    description: Confirms sensitive decisions like deleting a world.
    usage: |
            /<command>
  mvinfo:
    description: Gets world info.
    aliases: [mvi]
    usage: |
            /<command> [world] [page]
  mvenv:
    description: Tells the user all possible environment types.
    usage: |
            /<command>
  mvversion:
    description: Prints out version info.
    aliases: [mvv, mvver]
    usage: |
            /<command> [-b|-h|-p] [--include-plugin-list]
  mvhelp:
    description: Displays the Multiverse Help.
    aliases: [mvsearch, mvh]
    usage: |
            /<command> [filter] [page #]
  mvdebug:
    description: Turns on debugging.
    usage: |
            /<command> [1|2|3|off|silent]
  mvgenerators:
    description: Displays all found world generators.
    aliases: [mvgens]
    usage: |
            /<command>
  mvload:
    description: Loads a world into Multiverse.
    usage: |
            /<command> <world>
  mvregen:
    description: Regenerates a world Multiverse already knows about.
    usage: |
            /<command> <world> [-s seed]
  mvscript:
    description: Runs a script from the Multiverse scripts directory.
    usage: |
            /<command> <script> [target]
  mvclone:
    description: World clone command
    aliases: [mvcl]
    usage: |
            /<command> <world> <environment> [-g generator[:id]]
            /<command> creative grieftastic -- Creates a world called 'grieftastic' exactly identical to the world 'creative'.
  mvsilent:
    description: Reduces startup messages
    usage: |
            /<command> [true|false]
  mvgamerule:
    description: Sets a gamerule.
    aliases: [mvrule]
    usage: |
            /<command> <rule> <value> [world]
  mvgamerules:
    description: Lists the gamerules
    aliases: [mvrules]
    usage: |
            /<command> [world]
  mvanchors:
    description: Creating and removing Anchors command
    aliases: [mvanchor]
    usage: |
      /<command> <name> [-d]
  mvcheck:
    description: Validate your multiverse settings command
    usage: |
      /<command> <name> <destination>
  mvconfig:
    description: Configuration command
    aliases: [mvconf]
    usage: |
      /<command> <property> <value>
